export interface IMantenimiento {
  nombreEntidad: string,
  rolEntidad: string,
  anioEjecucion: string,
  mesEjecucion: string,
  duraMantPrg: string,
  duraMantCrr: string,
  duraMantEmg: string,
  cantMantPrg: string,
  cantMantCrr: string,
  cantMantEmg: string,
  mantenimientoCod: string,
  fechaInicio: string,
  fechaFin: string,
  horaInicio: string,
  horaFin: string,
  duracion: string,
  tipoMant: string,
  noDispDeg: string,
  paseProd: string,
  motivo: string,
  otrEntidad: string,
  prbDetec: string,
  comentAdicionales: string,
}
